### ISSUE TITLE
Support type 'varchar'

### ISSUE THREAD

**Issue by spencerwilson** [jeromew/node-pg-copy-streams-binary#15]
Hey! Neat package.

I'm trying to bulk load rows into tables whose text columns are conventionally of type `varchar` with a fixed length limit. [1]  If this package supported serializing JavaScript `string` values (sequences of UTF-16 code units) to Postgres's `varchar` binary format, then I could prepare my rows in JS (I have this part done already), turn them into a binary stream, and `COPY ... FROM STDIN` them into the tables.

It looks like the binary format for `varchar` is the same as that of `text`, which is the same in the two releases I care about:

- 12.4 (what we use, in Amazon Aurora PostgreSQL): [varchar](https://github.com/postgres/postgres/blob/REL_12_4/src/backend/utils/adt/varchar.c#L540-L548) -> [text](https://github.com/postgres/postgres/blob/REL_12_4/src/backend/utils/adt/varlena.c#L566-L578)
- 13.4 (current release): [varchar](https://github.com/postgres/postgres/blob/REL_13_4/src/backend/utils/adt/varchar.c#L539-L547) -> [text](https://github.com/postgres/postgres/blob/REL_13_4/src/backend/utils/adt/varlena.c#L578-L590)

Seems like this might be supportable by duplicating + adapting the existing support for `text`?

---

[1] The wisdom of this is admittedly debatable. Use case: examples of these columns not only include things like 2-letter [United States Postal Service state/territory abbreviations](https://pe.usps.com/text/pub28/28apb.htm) or 5-digit ZIP codes, but also arbitrary text from untrusted user input such as messages sent between users. In all cases, the API that controls read/write access to the data imposes limits on the lengths of these data. IIRC, we felt that it might make sense to consistently enforce the same limits in the database as well. I acknowledge this is contra the guidance that comes up when googling:

- ["Don't use varchar(n) by default"](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_varchar.28n.29_by_default) - PostgreSQL wiki
- https://dba.stackexchange.com/a/21496

**Comment by jeromew** [comment]
Hello,
sorry for the delay.

As you noted, varchar is in fact implemented as text in postgres and this is why I did not add support for varchar or varchar(n) in the library.

I understand how you can have a database with a schema using varchar or varchar(n) even though it may not be the recommended schema in postgres.

I did not implement many types because I am not yet sure how the type library should evolve. There are several questions :
 - performance : currently we convert each and every field that is read. The conversion between the postgres binary repr and the javascript in-memory representation has a important cost when there are many rows. Maybe we should keep the buffer repr for all fields and do the convertion just-in-time only when needed. Not yet sure how this should be implemented.
 - types implementation. There are several npm modules that approach the serialisation/deserialisation of fields from text repr or binary repr. It would probably be a good idea to try and see if a module could be used here instead of re-writing implementations of all the fields here. anyway if there is no module that does the job, a module is needed.
 - extensibility. As soon as you start trying to match someone's schema you probably need to find a solution for user implemented types that exist in postgres. You could also have cases where someone will want to have his/her own memory repr of a field (uuid is an example that comes to mind) so people need to be able to add their own types.

Regarding varchar, I will take a look at your PR but I am not yet sure to accept it if we cannot find an acceptable way to make the library work with varchar(n) definitions (I initially did not care about variable length types and did not look into how they impact the implementation).

Also I would prefer not the enter into the realm of encodings. Currently the library is written for the postgres backend configured with utf8 encoding which looks like a sane default to me.

**Comment by jeromew** [comment]
ok I merged the PR. Thanks. I thought that there was 2 types types in postgres (varchar and varchar(n)) but that is not the case as varchar(n) is implemented with modifiers on varchar.

So it seems that the binary protocol is not aware of the length limitations.

Note that the library does not do any check regarding the the length of the field and there is no test regarding what happens when trying to copy a too-long text into a varchar(n) so this potentially has the risk of opening a can of future issues.

If you have time to look at this it would be very interesting to have a test around limited length varchar to highlight what happens.
